services:
  database:
    image: postgres:14.18
    environment:
      POSTGRES_DB: subscription
      POSTGRES_USER: subscription
      POSTGRES_PASSWORD: Biplus@123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/opt/oracle/oradata
      - ./init_script:/container-entrypoint-initdb.d
    ports:
      - '5432:5432'
  kafka0:
    image: bitnami/kafka:4.0.0
    environment:
      BITNAMI_DEBUG: true
      KAFKA_CLUSTER_ID: merp
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:19092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka0:9092,EXTERNAL://localhost:19092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_CLUSTER_INITIALIZED: true
    ports:
      - '19092:19092'
  kafka1:
    image: bitnami/kafka:4.0.0
    environment:
      BITNAMI_DEBUG: true
      KAFKA_CLUSTER_ID: merp
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    ports:
      - '29092:29092'
  kafka2:
    image: bitnami/kafka:4.0.0
    environment:
      KAFKA_CLUSTER_ID: merp
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:39092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://localhost:39092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    ports:
      - '39092:39092'
  redis:
    image: redis:7.2
    ports:
      - '6379:6379'
volumes:
  pg_data: